version: '3'

services:
  nodejs:
    build:
      context: ..
      dockerfile: Dockerfile
    image: nodejs
    container_name: ll-api
    restart: unless-stopped
    env_file: production.env
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
    ports:
      - "80:48614"
      - "443:48614"
    volumes:
      - ../:/home/node/app
      - ../node_modules:/home/node/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: